import mongoose from "mongoose";
  
var uploadCsvSchema = new mongoose.Schema({  
    SrNo: String,
    Month: String,
    LoanAcNo: String,
    CustomerIDAPAC: String,
    LOSnoAPACReff: String,
    CustomerName: String,
    DisbDate: String,
    DisbLoanAmount: String,
    InsuranceAmt: String,
    VLIAddPayouton: String,
    PayoutRate: String,
    AddiSubvPayout: String,
    AddiSubvAmt: String,
    City: String,
    CircleCluster: String,
    State: String,
    PaidRate: String,
    Team: String,
    TME: String,
    Remark: String,
    GSTstatus: String,
    BilledOn: String,
    BankNBFCName: String,
    Product: String,
    SubProduct: String,
    Amt: String,
    GST: String,
    GST: String,
    BillNo: String,
    BillDate: String,
    ReceivedDate: String,
    Proper: String,
    ReceivedAmt: String,
    diff: String,
    FinalRate: String,
}); 
  
export default mongoose.model('DumbledoresArmy', uploadCsvSchema);